name: home_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  auto_route: ^9.3.0+1
  flutter_svg: ^2.0.17
  bloc_concurrency: ^0.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  gap: ^3.0.1
  responsive_builder: ^0.7.1
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  talker_flutter: ^4.6.14
  talker_dio_logger: ^4.6.14
  talker_bloc_logger: ^4.6.14
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.3.0

dev_dependencies:
  auto_route_generator: ^9.3.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14

  flutter_lints: ^4.0.0
flutter:
  generate: true

  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: ru
