// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyC-oftLhm1eRprD_-5_1ehU65NIKowQ',
    appId: '1:525943915998:web:94bc1a3192ba7bf267894f',
    messagingSenderId: '525943915998',
    projectId: 'home-management-85f32',
    authDomain: 'home-management-85f32.firebaseapp.com',
    storageBucket: 'home-management-85f32.firebasestorage.app',
    measurementId: 'G-7Z0N47LHWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wyRbf4aC8rAC_xEEahVOhR33dpJHYYc',
    appId: '1:525943915998:android:224dd62a6928d8af67894f',
    messagingSenderId: '525943915998',
    projectId: 'home-management-85f32',
    storageBucket: 'home-management-85f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8PE8iRagRTxSs73oxAnhhxky6L__KAO0',
    appId: '1:525943915998:ios:4f5e752034aca36c67894f',
    messagingSenderId: '525943915998',
    projectId: 'home-management-85f32',
    storageBucket: 'home-management-85f32.firebasestorage.app',
    iosBundleId: 'com.example.homeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8PE8iRagRTxSs73oxAnhhxky6L__KAO0',
    appId: '1:525943915998:ios:4f5e752034aca36c67894f',
    messagingSenderId: '525943915998',
    projectId: 'home-management-85f32',
    storageBucket: 'home-management-85f32.firebasestorage.app',
    iosBundleId: 'com.example.homeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtyC-oftLhm1eRprD_-5_1ehU65NIKowQ',
    appId: '1:525943915998:web:3c1f919f4a6f2ca767894f',
    messagingSenderId: '525943915998',
    projectId: 'home-management-85f32',
    authDomain: 'home-management-85f32.firebaseapp.com',
    storageBucket: 'home-management-85f32.firebasestorage.app',
    measurementId: 'G-TBX37XK6X4',
  );
}
